### ISSUE TITLE
Zone assignement

### ISSUE THREAD

**Issue by benbeton** [dotsam/homebridge-milight#1]
Hi,

the plugin is working, thanks! 
I want to understand how the zone assignement is done. 

When I configure (json.config) living "room lamp" how is the mapping to the right lamp in my living room done? 

regards

**Comment by dotsam** [comment]
Zones are simply assigned in order. So if you only specify one zone, that's zone 1. The second zone in the array becomes zone 2. If you skip a zone or have a zone that you don't want homebridge to control, you can put in `null` for that zone.

**Comment by benbeton** [comment]
thanks, perfect!
