### ISSUE TITLE
Switching between white and color

### ISSUE THREAD

**Issue by nitaybz** [dotsam/homebridge-milight#12]
Hi,

First of all I gotta say, you app works great, and super easy to implement, so thanks for that.

Second thing, I noticed that on my 'Home' app, when I switch between white color to RGB color I have to push the button twice for that to happen, it's not happening when I switch from RGB to white but only from white to color, that is weird, even between colors it works perfectly, only one press and it changes.
the fact that I have to turn it on twice makes it a bit hard to change to a scene with color when the bulb was white before. I have tried to set different values for the "delay" and "repeat" but nothing seems to work, any idea? does anyone else experienced it?

and one last thing, once in a while when I'm playing with my 'Home' app, I noticed that instead of changing the bulb to the color or brightness that I wanted, it just switch it to purple for some reason. that only happen sometimes and it might be related somehow to the first problem since it only happens when I play to much with tuning on and off and changing colors.

Please, your help!

**Comment by dotsam** [comment]
Hi @nitaybz,

This sounds like fallout from an issue I tried to fix in version 0.1.3 where some Homekit apps send hue/saturation in a different order, and I wasn't able to set the light to white mode properly at all.

I'm planning on coming up with a better solution that will wait a few milliseconds after either a hue or saturation command comes in before taking any action to ensure the right command is sent.

I'll see if I can either find more time to work on that change, or at least try and duplicate and put a fix in place for this issue.

**Comment by nitaybz** [comment]
That would be great, Thanks!
Waiting for your update...

**Comment by andyrooo82** [comment]
i'm also having the same issue as described by nitaybz. I've also tried different combos of delay/repeat with no luck. only seems to work on the second attempt. if you could help dotsam that would be awesome. Other than this love this app, great work!!

**Comment by andyrooo82** [comment]
Also slightly off subject I've noticed if the ligh is set to blue 10% for example and you ask Siri to change the colour to say, yellow, it'll also increase the brightness to 100% (so it doesn't keep the brightness setting)

Any ideas??

**Comment by dotsam** [comment]
Hi @andyrooo82, this is fixed in dev, and will be pushed out to npm either today or tomorrow.

**Comment by andyrooo82** [comment]
Awesome, thanks @dotsam I'll keep an eye out for it.

**Comment by nitaybz** [comment]
Hi @dotsam ! I just installed your dev branch and it did solved the switching white to color in one command so great thanks to you!! something else I noticed is that when switching from color to white it first switch it to red then immediately switch to white, all in one command so it really doesn't bother me as long as it turns white.

also I noticed what @andyrooo82 mentioned about the brightness issue, but I see that this one hasn't been fixed yet, still increasing the brightness to 100% when changing colors.

**Comment by dotsam** [comment]
@nitaybz Just tested this myself, and I get the same behaviour when asking Siri to change the colour of a light, but not when using the Home app, or Eve. So there's no bug in my code, Siri is simply setting the brightness, hue, and saturation (only used on the newest full colour bulbs) to predefined values when you say "blue" or "green".

**Comment by nitaybz** [comment]
yes you are right... it is doing it only when using Siri!

what is the full color bulb? and will i be able to change the saturation of RGBWW bulb? is that even possible?

**Comment by andyrooo82** [comment]
@dotsam That makes sense, it's only doing the weird brightness thing when using Siri not Home or Eve. How do I  use the dev version or wil it be master soon?

**Comment by nitaybz** [comment]
@andyrooo82 , you can use `sudo npm install -g https://github.com/dotsam/homebridge-milight.git#dev`

**Comment by andyrooo82** [comment]
Thanks @nitaybz do I need to uninstall the milight plugin first or will this overwrite? sorry first time i've installed from dev.

**Comment by nitaybz** [comment]
it will overwrite... and to be honest, I just found out how to do it yesterday :) cause I wanted this update as well

**Comment by andyrooo82** [comment]
nice one, cheers @nitaybz

**Comment by andyrooo82** [comment]
just gave it a quick test and seems to be working great! when setting from colour to white there is a very brief period of red but Stevie Wonder would be happy to see it. Thanks for the hard work @dotsam

**Comment by andyrooo82** [comment]
Been testing this for a bit now and sometimes when setting to white either via Siri or setting a scene (so programmed to be white) it goes red. Has anyone else noticed this?

**Comment by dotsam** [comment]
@andyrooo82 yes, this is because of how Homekit Apps/Siri send the hue and brightness commands to the plugin. They're not always sent in the same order, so when either command is sent, there's some checking done to try and determine what should happen no matter which command is sent first.

In the future, I have plans to implement a small delay before either command takes effect to wait for any other command that might affect the colour of the bulb.
