### ISSUE TITLE
Wall Switch Option

### ISSUE THREAD

**Issue by andcape** [dotsam/homebridge-milight#13]
Hello dotsam. I found you code some weeks ago and it is working so nice that I started thinking in newer possibilities, but I am really new working with homebrigde.
I was thinking about making an additional command when turning the lights on and off the milights to drive a relay (powered by an ESP8266) through HTTP, this way we could better control the on/off state through home app, because without it the wall switch must be always on.
As I have several "traditional" bulbs in my room, along with the milights, I already have an ESP8266 working as a smart switch.

Do you have any idea if this is something difficult to implement? I will do some tests and try to make it work...

Thanks for the nice plugin you developed.

**Comment by dotsam** [comment]
Hi @andcape, this is probably outside the scope of this plugin, but doing a quick Google search for "esp8266 homebridge relay", it looks like lots of people have implemented this in various different ways, so hopefully you'll be able to find something that works for you.
