### ISSUE TITLE
Combining 2 lights in 1 config

### ISSUE THREAD

**Issue by flipmoo** [dotsam/homebridge-milight#15]
Hi there

I own a v3 wifi controller + 1 rgbw bulb and 1 rgb ledstrip controller.
Both work fine trough the milight app. (button 1 bulb, button 2 strip.)
But i only get 1 working trough homekit. 

this is the current config: (gang = the bulb & kast is the strip)
{
  "platform": "MiLight",
  "name": "MiLight",
  "bridges": [
    {
      "ip_address": "192.168.2.14",
      "version": "v3",
      "lights": {
        "rgbw": [
          "Gang"
        ],
        "rgb": [
          null,
          "Kast"
        ]
      },
      "repeat": 1,
      "delay": 30
    }
  ]
},

**Comment by heikodede** [comment]
I don't have rgb lights, but in the readme you can find this detail "RGB lamps can only have a single zone".
I didn't find any example config, but just try some possibilities (just one array entry / no array, just a string / ...).
I hope this will help you :)

**Comment by dotsam** [comment]
@flipmoo Most of the RGB LED strip controllers I've seen actually act as an RGBW bulb, and since you're controlling them on the same screen of the milight app as your RGBW bulb, that would seem to be the case for you too. So add "Kast" as the second item in your RGBW array and remove your RGB item and things should work.

**Comment by flipmoo** [comment]
Could you please show me the config example of the correct way form implementing the "second item"?

**Comment by flipmoo** [comment]
With this config i see both "buttons" in homekit but both buttons (gang & kast) control the bulb but not the LED strip.

{
		"platform": "MiLight",
		"name": "MiLight",
		"bridges": [{

			"ip_address": "192.168.2.14",

			"version": "v3",

			"lights": {
				"rgbw": ["Gang"],
				"rgb": ["Kast"]
			},
			"repeat": 1,
			"delay": 30
		}

**Comment by flipmoo** [comment]
And when is use rgbw vor the Kast (led strip) as well i get an error in jsonlint on twice using rgbw

**Comment by dotsam** [comment]
Your config should look like this:
```
{
"platform": "MiLight",
"name": "MiLight",
"bridges": [{
		"ip_address": "192.168.2.14",
		"version": "v3",
		"lights": {
			"rgbw": ["Gang", "Kast"]
		},
		"repeat": 1,
		"delay": 100
	}]
}
```

**Comment by flipmoo** [comment]
YES That works! thanks!
But i do have 1 additional question.
Are the color settings fixable?
it does react to the color change option, but it doesn't match the color.

**Comment by flipmoo** [comment]
Hi there, i'm still looking for a fix the match the color setting ont my mobile with the LED strip.

**Comment by dotsam** [comment]
Are the colours wrong with the MiLight app? If so, you probably need to check the r/g/b wires from your light strip to the controller.

**Comment by dotsam** [comment]
Closing as no response. Please follow up if this plugin is producing different colours than the milight app.
