### ISSUE TITLE
Cant get the lights working

### ISSUE THREAD

**Issue by netzpixel** [dotsam/homebridge-milight#16]
I'm using homebridge quite long now. Today my mi lights arrived and I tried to make them work with homebridge, but nothing I do gets them to work.
But I'm also not sure what type of lights I have. I ordered those:
https://www.aliexpress.com/item/4pcs-9W-E27-LED-RGBCW-or-RGBWW-bulb-Milight-AC85-265V-Four-Zone-Remote-WiFi-Controller/32653225173.html?spm=2114.13010608.0.0.d0GZUz

So I guess those are the rgbw ones. If I change them to fullColor in the config, I get no response from any device. With the setting below I can use everything as usual but the mmi lights don't work. I can't turn them off, nor change color...
Also I don't know the names of the bulbs. I named them Zone1 - 4 because they are called that way in the "Mi-Light 3" App.

I hope someone can help me. Without homebridge they do work btw...
I tried adding the IP of the bridge, but that didn't change a thing.

{
    "platform":"MiLight",
    "name":"MiLight",
    "bridges": [{
      "lights": {
        "rgbw": ["Zone1", "Zone2", "Zone3", "Zone4"]
      }
    }

**Comment by heikodede** [comment]
I think you forgot the version. It's important, because iBox 2 doesn't work with the default value - v6 worked for me. Just add this. And adding ip address could also be a good idea. Just look for it in your router web frontend.

Here is a copy of my own config. Maybe it will help you.
`        "platforms": [
                {
                        "platform": "MiLight",
                        "name": "MiLight",
                        "bridges": [
                                {
                                        "ip_address": "192.168.178.26",
                                        "version": "v6",
                                        "lights": {
                                                "rgbw": ["NameYourZoneOne", "NameYourZoneTwo", null, null]
                                        },
                                        "repeat": 1,
                                        "delay": 30
                                }
                        ]
                }
        ]
`

**Comment by bentheone** [comment]
I added the version and the ip but still no reaction ... :(

**Comment by netzpixel** [comment]
Ok, thanks. It works now after restarting everything. I only wonder how to use the bulbs with the bridge AND the remote. After linking everything with the remote, the wifi thing isn't working anymore and the other way around.

**Comment by heikodede** [comment]
For me it worked when I first connected the bridge with the bulbs and when I could control them via app then pair with the remote. I read that it just works in this order and not other way around.
