### ISSUE TITLE
Connection stops working after ~10 minutes

### ISSUE THREAD

**Issue by heikodede** [dotsam/homebridge-milight#17]
Hey,

I hope this is the right place to write about my issue. I ordered some rgbw-milight-bulbs and a wifi bridge. There's just an "iBox 2" written on the box. I can't find any further details about the exact version (same with the web frontend).

So let's come to the details. Configuration worked fine. Found out that it has to be v6 by trial and error.
After a random time (mostly between 7-15 minutes) it stops working. Homebridge is still running and other homebridge accessories still work (beside "homebridge-milight"). I still can switch the devices on and off in the app, but nothing happens with the bulbs. Restart homebridge made it work again, so I got a crontab that restarts the homebridge server every 6 minutes, but that's a dirty solution.

I also started homebridge in debug mode. Here's the part where everything worked fine:
`EventedHTTPServer [::ffff:192.168.178.140] HTTP request: /characteristics +5s
  HAPServer [CC:22:3D:E3:CE:34] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":11,"iid":9,"value":0}] +1ms
  Accessory [Homebridge] Setting Characteristic "On" to value 0 +1ms
[1/15/2017, 4:48:14 PM] [MiLight] [IKEA] Setting power state to off
  EventedHTTPServer [::ffff:192.168.178.140] Muting event '11.9' notification for this connection since it originated here. +2ms
  EventedHTTPServer [::ffff:192.168.178.140] HTTP Response is finished +1ms`

And here's some debug information when it didn't work. I can't see any problem/difference.
`    EventedHTTPServer [::ffff:192.168.178.140] HTTP request: /characteristics +8s
  HAPServer [CC:22:3D:E3:CE:34] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":11,"iid":9,"value":0}] +2ms
  Accessory [Homebridge] Setting Characteristic "On" to value 0 +0ms
[1/15/2017, 5:31:03 PM] [MiLight] [IKEA] Setting power state to off
  EventedHTTPServer [::ffff:192.168.178.140] Muting event '11.9' notification for this connection since it originated here. +2ms
  EventedHTTPServer [::ffff:192.168.178.140] HTTP Response is finished +1ms`

If you need any further information, feel free to ask :)

**Comment by dotsam** [comment]
Hi @cheapjoe,

This is the same issue we've discovered in #10 and @mwittig is working on in https://github.com/mwittig/node-milight-promise/issues/7

Essentially, the new bridges are session based, but since Homebridge is a long-running program and could receive commands at any time, that session needs to either be kept open or re-opened when it closes/times out (which seems to be around 10 minutes).

Closing this as I'm keeping track of this issue in #10

**Comment by heikodede** [comment]
Oh. Thank you very much for your fast answer. Sorry that I didn't read this!
You're doing a great job. Have a nice day :)
