### ISSUE TITLE
using more then one wlan bridge

### ISSUE THREAD

**Issue by benbeton** [dotsam/homebridge-milight#2]
Hi Sam.

thanks for answering my last question. 
Is it possible to use (include) a second or third ulna bridge. I'm considering to by a second one.

thanks

**Comment by dotsam** [comment]
Right now you can just define another Milight platform in your config.json, but I'm planning an update soon where it can all be done under a single platform entry.

**Comment by dotsam** [comment]
The new config style has been implemented in the latest release.
