### ISSUE TITLE
WW/CW LED Strip Controller not working

### ISSUE THREAD

**Issue by Struder47** [dotsam/homebridge-milight#20]
Sorry to create an issue for this!
I have a problems getting the following setup to work (please excuse my english):

Hardware: Milight Bridge ibox2 + WW/CW Led Strip Controller + home bridge (running on a raspberry pi):

The relevant part of my config.json looks like this: 

{
            "platform":"MiLight",
            "name":"MiLight",
            "bridges":
              [
              {
                "ip_address": "192.168.178.31",
                "version": "v6",
                "lights": {
                          "white": ["Light"]
                          },
                "repeat": 1,
                "delay": 300
              }
              ]
         }

Using the milight app the control of the LED Strip works just fine. 
But when I use home bridge I get the following issue:

The lamp is shown in the iOS homekit app (strangely as an device wich can also change colors). I can dim/turn off/on the light in the home kit app, but there is no change of the lamp...
I already tried changing the delay etc...but no change...

Maybe there is no support of the WW/CC LED Strip Controller yet?

Thanks in advance for any idea to solve the problem!!!

**Comment by dotsam** [comment]
Can you confirm what "page" of the MiLight app you're using to control the light strip? I've got a feeling that they're actually using the command sequence for rgbw bulbs. Can you try using type rgbw instead of white in your config.json instead of white and see if that works?

(As for having colour adjustment available in HomeKit apps for white bulbs, there's no other way to allow adjustment of colour temperature that I know of, but I haven't actually played around with the characteristics much in iOS 10, so I might look in to that again)

**Comment by Struder47** [comment]
Thanks for your fast reply. 
As long as i don't touch the color selector in the milight app I can use the brightness slider on the hue page of the app. As soon as I touch the color selector that method does not work anymore. 



However I can always use the WW/CW Page on the app, as long as the colortemperatur slider is set to "warm".




I tried your idea of changing the type to rgbw, but sadly it still does not work...

**Comment by Struder47** [comment]
Any other idea?

**Comment by dotsam** [comment]
Hi @Struder47, can you provide a link to more info about the WW/CW Led Strip Controller you have? I'm still not 100% clear if the strip controller is acting as a RGB, RGBW, or "Full Colour" bulb.

**Comment by Struder47** [comment]
That is the controller I am currently using: 

http://www.gearbest.com/led-accessories/pp_572162.html?wid=21

**Comment by haudegen9** [comment]
Have the same hardware and the same issue. The stripe reacts perfectly with the milight app but never get any change in the light with homekit. Tried every type of bulb.

**Comment by dotsam** [comment]
So it looks like this should be set to the "white" bulb type. @mwittig looks to have discovered the byte sequence for white bulbs on the v6 bridge himself, so maybe he could chime in here with more details or troubleshooting steps.

**Comment by mwittig** [comment]
Hi, unfortunaetly I don't own a WW/CW Led Strip Controller for testing. I have dual-white bulbs which I can successfully drive using´the "commands.white" command set. See the following example for dual-white - https://github.com/mwittig/node-milight-promise/blob/master/examples/example-dual-white-v6.js

As @Struder47 said he "can always use the WW/CW Page on the app" I think the WW/CW Led Strip Controller should react to same command set as the dual-white bulbs

**Comment by haudegen9** [comment]
Tried the commands white, rgb and rgbw and never get a change. :(

**Comment by dotsam** [comment]
@Struder47 @haudegen9 Are you able to try the example code at https://github.com/mwittig/node-milight-promise/blob/master/examples/example-dual-white-v6.js (you'll need to clone the repo and do an `npm install` beforehand) and let me know if it works?

**Comment by Struder47** [comment]
OK, i tried the different examples. Here is what I found out:

-  I am definitiv using a v6 bridge, as the discover-bridges-v6.js gives me:
  [ { ip: '192.168.178.31',
    mac: 'F0:FE:6B:16:8B:44',
    name: 'HF-LPB100',
    type: 'v6' } ]

-  I don't get any change of the light running the different examples except
    for the example-full-colour.js
When the example-full-colour.js is finished the light suddenly turns itself off. I can only reactivate the light, by touching the color temperature selector on the WW/CW Page of the app. I guess it is the same issue when I touch the color wheel on the hue page of the app.

Sadly the example-dual-white-v6.js does not have any impact at all...

**Comment by haudegen9** [comment]
@dotsam Sorry, i can't install the repo, because homebridge runs in a docker on a synology.

**Comment by Struder47** [comment]
Any way we can support you in implementing the support for the WW/CW controller?

**Comment by mwittig** [comment]
Which WW/CW controller page are using exactly? I have been using the following page showing the remote which should be supported by the WW/CW strip controller you have.  As you said the controller is acting strange in your setup: *"As long as i don't touch the color selector in the milight app I can use the brightness slider on the hue page of the app."* I don't have this behavior with the WW/CW bulbs I am using. Please try to unlink the strip controller and pair it again using the Milight App with the remote control selected as shown below. You don't need to use link/unlink for this, but just pressing the green "ON" button multiple times should do.

![image](https://cloud.githubusercontent.com/assets/6117742/23306014/aba947ac-faa1-11e6-89f1-fcf2a1c0357a.png)

![image](https://cloud.githubusercontent.com/assets/6117742/23306271/0a8e2d2c-faa3-11e6-8225-91bb3e434145.png)

**Comment by Struder47** [comment]
You guys are awesome. Now it is working! I had the wrong remote selected. I only had to unpair the device, select the proper remote and then pair it again.

Thx so much!
