### ISSUE TITLE
Milight iBox led light

### ISSUE THREAD

**Issue by jgerits** [dotsam/homebridge-milight#21]
The iBox has his own light. I am not able to control that light in any way. Am I doing something wrong or is this not implemented jet?

**Comment by dotsam** [comment]
@zelda1link3 I'm working on implementing this now, will likely be pushing a new version in the next day or two.

**Comment by dotsam** [comment]
I've just published 0.1.9 which now supports the "bridge" bulb type to control the built-in bridge LED. Let me know if it works for you, as I don't have a v6 bridge to test with.

**Comment by jgerits** [comment]
@dotsam  It turns on and off only the light is very dim (even at 100% it is not realy 100%) but i can turn it on and off and that is a great start i think. I could switch it 1 time to blue and it turned on 100% after that one time if i click on a color it wont change but it will turn on on very low light.

**Comment by jgerits** [comment]
@dotsam what do you think that it is better to close this bug and create a new one with the brightness error?

**Comment by dotsam** [comment]
Let's leave this issue open. I think I've found the issue, so I'll try and get a fix out in the next day.

**Comment by jgerits** [comment]
I tried with commit f671f04d0674cad19d4a6f4ad70acef0cd0477dd.
The brightness is solved only the colors work kinda but i can't get it to white anyway.

**Comment by dotsam** [comment]
White mode should be enabled when the saturation is set to 0 at any hue. Asking Siri to set the light to white should work fine. How are the colours different?

**Comment by jgerits** [comment]
The strange thing is the following:

[2/11/2017, 8:29:26 AM] [MiLight] [Slaapkamer] Saturation is 0, making sure bulb is in white mode
[2/11/2017, 8:29:26 AM] [MiLight] [Slaapkamer] Setting saturation to 5 (NOTE: No impact on bridge MiLight bulbs)

this one turns it to white.

But 

[2/11/2017, 8:30:06 AM] [MiLight] [Slaapkamer] Setting hue to 0
[2/11/2017, 8:30:06 AM] [MiLight] [Slaapkamer] Setting saturation to 0 (NOTE: No impact on bridge MiLight bulbs)

that one is a random other color (if i have the color weel it is on white but it gets the color that is on the end of the weel.

**Comment by dotsam** [comment]
@zelda1link3 Can you test this with the just-released 1.0.0 and let me know if this is still a problem? Thanks.

**Comment by jgerits** [comment]
@dotsam it works great now thanks for your effort
