### ISSUE TITLE
Milight (v6) Controller - Set protocol to UDP

### ISSUE THREAD

**Issue by opauwels** [dotsam/homebridge-milight#23]
Hi,

This is not really an issue but more of a heads-up/reminder as this does not seem to be mentioned in the installation/readme files.
So perhaps this is noteworthy enough to add it to the read-me files or installation information.

Both a friend of mine and myself have Milight v6 controller bridges and raspberry pi's with homebridge installed. However we both could not get the homebridge-milight plugin to work, the requests were being sent (without any errors in debug mode) to the controller but nothing happend.

We've just found the problem, the controllers were set up to use the TCP protocol in its settings, however the plugin sends the requests using UDP.

If you go the the (web) admin panel of the milight controller by surfing to its ip address: 192.168.x.x and logging in with admin/admin, you can go to the "Other setting" tab and set the protocol to UDP, after doing so you get the option to reboot the controller which you should do.

After that everything worked and we're now able to control the lights using SIRI.

Screenshot of the web-admin setting:
![schermafbeelding 2017-02-12 om 14 53 53](https://cloud.githubusercontent.com/assets/14878881/22862664/716b5ba6-f133-11e6-82b7-014c9ace6a72.png)

**Comment by mwittig** [comment]
Thanks for the info. Seems like there are different firmware versions in the field already. My controller was set to UDP by default. Wich firmware version do you have?
