### ISSUE TITLE
Can't get my bulb working. 

### ISSUE THREAD

**Issue by Downlosc** [dotsam/homebridge-milight#25]
Hi, i have a controller MiLight (not sure which version it is) but i can't get it working. 
I tried setting it up in the json file with all the bridge's type (fullColor, rgbw...). 
I get an "Unhandled rejection Error: no response timeout" when starting the server. 
The bulb lights up for a second or less when i tap on the accessory in homekit. But this does not happen every time i tap on the app. It seems to be random. 

this is my internet controller. 
https://www.google.it/search?q=milight+controller&client=ubuntu&hs=PR9&channel=fs&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjowJyrqrrSAhWCaxQKHdKqAwcQ_AUICSgC&biw=1920&bih=946#imgrc=dCqhUOO178bYCM:

**Comment by SkyJohn** [comment]
What kind of bulbs are you trying to control? Do you have them set up and working in the milight app?

Can you show your config file?

**Comment by Downlosc** [comment]
Yeah i did set them up on the app and they are perfectly working. 
`  GNU nano 2.2.6                                                                  File: config.json                                                                                                                                            

{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51827,
    "pin": "031-45-154"
  },

  "description":"file config",

  "accessories":[],

  "platforms":[
    {
      "platform":"netatmo",
      "name":"netatmo weather",
      "ttl":5,
      "auth":{
        "client_id":"+++++++++",
        "client_secret":"+++++++++",
        "username":"+++++++",
        "password":"+++++++++"
      }
    },
{
            "platform":"MiLight",
            "name":"MiLight",
            "bridges": [
              {
                "ip_address": "192.168.1.5",
                "port": "8899",
                "version": "v6",
                "lights": {"fullColor": ["Bedroom", null, null, null]
                },
                "repeat": 1,
                "delay": 50
              }
            ]
        }
  ]
}



`

**Comment by Downlosc** [comment]
Sorry, i still dont know how to paste code here

**Comment by SkyJohn** [comment]
Does the light controller look exactly like the one in the image you posted?

If it does then you need to change the version number in the config to either v2 or v3 (not sure which will work). v6 is for a later model that has a different looking label on the front.

**Comment by Downlosc** [comment]
Yes it does look like that one. 
Ok i'll try to change to v2, i've tried v3 a few days ago and it didnt work. Hope v2 works!
Keep you up to date.

**Comment by toshibochan** [comment]
did work?

**Comment by toshibochan** [comment]
try this
"ip_address": "192.168.1.5",
"lights": {"fullColor": ["Bedroom"]},
"repeat": 3,
"delay": 80
