### ISSUE TITLE
CW/WW led strip controller color temperature

### ISSUE THREAD

**Issue by alexij1997** [dotsam/homebridge-milight#29]
Hello, I have issue.(Partly associated with Issue #20  )
How I can adjust Kelvin(color temperature) via HomeKit for CW/WW led strip controller?
Now I can adjust only brightness and turn on, turn off the lamp.
In HomeKit, there is a color adjustment tab (RGB), but when I choose white color it changes lamp color to white (as it should be) - in HomeBridge log it looks like - 

[MiLight] [Lamp] Setting hue to 0 
[MiLight] [Lamp] Saturation set to 0, setting bulb to white

Any other value other than 0 does not work.

Works as a "fullcolor" simultaneously for two LED controllers (RGB and CW/WW),
RGB - fully correctly works. 
CW/WW - working, but not adjustable color temperature.(problem!)

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:31",
		"port": 55141,
		"pin": "031-45-155"
	},
	"platforms": [{
		"platform": "MiLight",
		"name": "MiLight",
		"bridges": [{
			"ip_address": "192.168.1.242",
			"version": "v6",
			"zone": "1",
			"lights": {
				"bridge": ["Router"],
				"fullColor": ["Lamp", "Strip"]
			},
			"repeat": 1,
			"delay": 30
		}]
	}]
}

Thank you.

**Comment by dotsam** [comment]
I'll be resolving this in #26. The official HomeKit colour temperature characteristic was only recently documented, so before now there was no way to cleanly separate RGB colours from colour temperature.
