### ISSUE TITLE
basic usage question

### ISSUE THREAD

**Issue by duecedriver** [dotsam/homebridge-milight#30]
I am using the homebridge plugin to home-assistant...

I have this plugin installed but dont have it defined in the homebridge config.json and it seems to work ok... although this plugin can do more and acts differently than home-assistant.. i.e. night light mode

so my question...

provided the 'main' control layer is home assistant.. .should the only config device in the homebridge config.json be home assistant.. i.e. will adding home bridge-milight to the config.json interfere with the functions and sync to home assistant?

I would love to be able to get all the features that are provided here light nightlight mode.. and possibly the bulb 'disco modes' etc.. right now home assistant has basic milight function, on-off, color and starturation 

its one glaring issue is that the new versions of the bridge allow 4 groups of every bulb type and home-assistant seems to get confused.. ie when I have bulbs on rgbww 1 and white 1 their functions sometimes collide 

anywho.. thanks for those that take the time to weigh in and give me a best practices setup for this ...

**Comment by duecedriver** [comment]
anyone.. bueler.. is this mike on ... hehe

**Comment by SkyJohn** [comment]
Using both this plugin and the Home Assistant/Homebridge one wont cause any conflicts, other than obviously giving you duplicates of all your lights in the Home app, and having this plugins settings not sync up with Home Assistant.

As far as I know you can't get access to things like the disco function with this plugin either.

And the issue with different kinds of bulbs colliding has happened to me as well when using both Homebridge and Home Assistant as the backend, I think thats more of an issue with the signals the Milight control boxes are sending out, they aren't really designed to have more than one type of light hooked up to them at the same time.

IMO there are no real advantages to installing this plugin as well if you're already using Home Assistant and the Home Assistant/Homebridge plugin, you don't get any extra features with this plugin and things from this plugin wont sync up with whatever Home Assistant is doing.

**Comment by mwittig** [comment]
Wow, this sounds really depressing! Github, can I please give another star to the author of the project to appreciate his work? Thanks!

**Comment by SkyJohn** [comment]
I wasn't saying anything bad about the plugin it works perfectly and I've been using it for months, I was just saying there is nothing to be gained from OP to be running this plugin if he is already using a Home Assistant system to control his Milights because they both do exactly the same job.

**Comment by duecedriver** [comment]
@SkyJohn 

thanks for the info.. I figured that if I installed it in homebridge along with home-assistant I would get double devices and probably chaos...

and to be clear

@mwittig 

lovin the plugin ... dont know if its doing anything for me right now.. i.e. if home assistant is using it or not. but with home assistant piped through homebridge I get siri voice control over my lights

just wish that home assistant had some of the milight API features that you support.. perhaps you can give them a leg up on the commands


the issue with cross controlling between lights I think is a home assistant issue

when using the milght iphone app.. they keep the rgb/white/rgbww separate ... although use different virtual remotes for the rgbww...  but I can change the state of white lights without turning on the rgbww which is what was happening under home assistant .. again perhaps you guys can help straighten them out.... 

thanks for the support..

**Comment by dotsam** [comment]
If my plugin isn't configured, it won't be doing anything. And since MiLight only has one-way communication and no concept of state, I suggest you pick only one way of controlling your bulbs, so that there is some consistency for on/off/colour state.

If you want more features from Home Assistant, you should open an issue at https://github.com/home-assistant/home-assistant
