### ISSUE TITLE
WiFi Box LED

### ISSUE THREAD

**Issue by samsonrosen** [dotsam/homebridge-milight#36]
Hi! I have the V3 box. Is there a way to get the LED to show as a Light in Homekit? Do I need to add something to my config..

Thanks,

Sam

**Comment by dharrison8815** [comment]
I added my v6 hub as two separate devices. One for the four groups and one for the hub itself both with the same IP address. I've pasted this portion of my config file below:

 {
					"ip_address": "10.0.1.7",
                    "version": "v6",
					"lights": {
						"fullColor": ["Kitchen", "Island", "Pendant", "Entryway"]
					}
				},
                            {
					"ip_address": "10.0.1.7",
                    "version": "v6",
					"lights": {
						"bridge": ["Hub"]
					}

Hope this helps!

Dusty

**Comment by dotsam** [comment]
@samsonrosen Yes, you'll need to add the "bridge" bulb type to your lights object as below.

@dharrison8815 This should be in a single bridge like below:
```json
{
  "ip_address": "10.0.1.7",
  "version": "v6",
  "lights": {
    "fullColor": ["Kitchen", "Island", "Pendant", "Entryway"],
    "bridge": ["Hub"]
  }
},

**Comment by samsonrosen** [comment]
Hi @dotsam, 

Sorry for the delay in the response! I have added the configuration but nothing happens in my Homekit app. I have noticed I am getting an error when initialising Homekit however.

```
  {
         "platform":"MiLight",
         "name":"MiLight",
         "bridges":[
            {
               "ip_address":"255.255.255.255",
               "version":"v6",
               "lights":{
                 "bridge":[
                    "Landing"],
                  "rgbw":[
                     "Light","Lamp"]
               },
               "repeat":3,
               "delay":5
            }
         ]
      },
```

```
[23/09/2017, 05:52:49] [MiLight] Initializing MiLight platform...
[23/09/2017, 05:52:49] [MiLight] Invalid light type specified.
[23/09/2017, 05:52:49] [MiLight] Initializing platform accessory 'Light'...
[23/09/2017, 05:52:49] [MiLight] Initializing platform accessory 'Lamp'...
```

**Comment by dotsam** [comment]
Can you confirm what version of the plugin you currently have installed with `sudo npm list -g homebridge-milight`?

**Comment by samsonrosen** [comment]
Hi!

V0.1.7

**Comment by samsonrosen** [comment]
Goodness! I apologise, I definitely ran the update command yesterday... I just used the install command and it’s brought me up to date and the plugin works again!!!

Thanks so much for making this the most cost efficient lighting set on the market!!
