### ISSUE TITLE
Control not possible with Home App

### ISSUE THREAD

**Issue by jannnfe** [dotsam/homebridge-milight#38]
Hello,
I bought this MiLight iBox2 (idk. witch version v1-v6?) and this RGBW Bulb.
With the MiLight App everything is working fine!
I try to integrate this MiLight System into my HomeKit Homebridge. 

![img_6188 2](https://user-images.githubusercontent.com/30130742/30699816-0705a440-9ee6-11e7-8b44-186b6fec5cd3.jpg)
![img_6189 2](https://user-images.githubusercontent.com/30130742/30699817-07227b56-9ee6-11e7-9195-ebaaa3037fd1.jpg)

In the Webinterface of the iBox I gave the iBox a static IP-address and changed Protocol to UDP.
I opend the port 8899 on my Linux Server.
In the config.json of Homebridge I define the static IP-address.

config.json:
> "platforms": [
>     {
>       "platform": "MiLight",
>       "name": "MiLight Bridge",
>       "bridges": [
>         {
>           "ip_address": "192.168.178.19",
>           "port": "8899",
>           "version": "v6",
>           "lights": {
>             "rgbw": [
>               "Schreibtisch"
>             ]
>           },
>           "repeat": 3,
>           "delay": 100
>         }
>       ]
>     }

On v6 version I get this error output, but on all other versions the control with the Home App dosen't work, too:
`Unhandled rejection Error: no response timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-milight/node_modules/node-milight-promise/src/milight-v6-mixin.js:125:26)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)`

Can anybody help me to get my MiLight working with Apple Home App?
Thanks!

**Comment by dotsam** [comment]
The port for v6 bridges should be `5987`, or just leave it out of your `config.json` to use the default.
