### ISSUE TITLE
single bulb not supported in Homekit

### ISSUE THREAD

**Issue by zuroph** [dotsam/homebridge-milight#44]
I've expanded my set up, adding in a second iBox, and updating my config file.

Prior to this, after a recent reset, one bulb in my set up would not be recognised by the Home app. It would appear in the home app in "Default room" state that it wasn't supported by Homekit, and was uneditable, so could not be removed.

I hoped that this would be resolved when I added the second iBox. I moved the affected bulb from iBox 1 to 2, and it worked! I completed set up, and just realised that the iBox 2 itself is now showing the same issue. the bulb linked through it now works fine, but the iBox 2 itself now shows in default room in home app, and says its not supported by home kit. Its again unlovable, and unediteable. 

Below, the "Null" on the rgbw line of ip..101 is where the problem bulb previously was. 
once that bulb was moved to iBox 2 and renamed Ella, it now works.
now its the bridge labelled "Lilli" that doesn't load in home App. 

Both times, they've worked fine in the milight app. 

  _{
          "platform":"MiLight",
          "name":"MiLight",
          "bridges": [
            {
              "ip_address": "192.168.0.101",
              "version": "v6",
              "lights": {"bridge": ["ibox"],
                "fullColor": [null,"Bedroom",null,null],
                        "rgbw": ["Kitchen","Sittingroom","Corner lamp",null]},
              "repeat": 1,
              "delay": 30
            },
          {
             "ip_address": "192.168.0.24",
             "version": "v6",
             "lights": {"bridge": ["Lilli"],
                      "rgbw": [null,null,null,"Ella"]},
             "repeat": 1,
             "delay": 30
           }_
![img_7074](https://user-images.githubusercontent.com/24573022/33712067-06942650-db3e-11e7-9941-67d093e50a81.PNG)

Any ideas? quite confused that it moved to another bulb on a different bridge.

**Comment by dotsam** [comment]
Hi @zuroph,

Lights currently get a UUID based only off of their name, so if there's an issue with it in the HomeKit database, even if your move it to a different bridge, that will still be an issue.

I'd start troubleshooting by removing the problem light from your config, starting Homebridge, and waiting for it to see the change and remove the light. Then add it back and see if it works. If you don't have any luck with that, you'll probably have to re-pair with Homebridge, starting with removing the `persist` folder (see https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting for more info) and potentially deleting and re-creating your "Home" on your phone too. You may even need to change the MAC of the Homebridge bridge as well.

For any more support, I'd try the Homebridge Slack or reddit (linked here https://github.com/nfarina/homebridge#community)
