### ISSUE TITLE
color

### ISSUE THREAD

**Issue by derrinbeek** [dotsam/homebridge-milight#58]
hi how can you set the color for a light to blue or red etc i can't find it

Derrin616

**Comment by toshibochan** [comment]
![09bbfb79-0176-4fd2-8b9c-896a5a75e4bb](https://user-images.githubusercontent.com/15816913/50340089-daf30300-055c-11e9-8d49-3e0fae90e1be.jpeg)

**Comment by derrinbeek** [comment]
hey Im using your NPM package with javascript

**Comment by dotsam** [comment]
This package is designed exclusively for use with Homebridge. If you're looking to communicate more generically with MiLight bulbs, you probably want to look at the underlying library I use, https://github.com/mwittig/node-milight-promise
