### ISSUE TITLE
Error on Homebridge 1.3.1

### ISSUE THREAD

**Issue by elo111** [dotsam/homebridge-milight#75]
Hello,
do you already have a solution for the problem, the Homebridge starts, but the connection to the Apple Home APP is no longer established.

**Comment by dotsam** [comment]
Can you provide any more details here? I don't believe my plugin generates any issues that would prevent Homebridge from loading correctly.

**Comment by elo111** [comment]
Sorry, but I have the same problems as some others. I just read the entries too late.

homebridge-milight] This plugin generated a warning from the characteristic 'Color Temperature': characteristic was supplied illegal value: number 140 exceeded minimum of 153. See https://git.io/JtMGR for more info.

I saw that since today you provide an update (1.16) because of this problem. Will install it tonight.

Thanks a lot for your quick help.

**Comment by elo111** [comment]
Hello,
with today's update of milight 1.1.6 my homebridge under 1.3.2 works perfectly again.


kind regards

Von meinem iPad gesendet

Ernst Lochbühler
