### ISSUE TITLE
Select bulb every time

### ISSUE THREAD

**Issue by jameswood** [dotsam/homebridge-milight#76]
We have a mix of Alexas, Siris and rf remotes — and family habits around which ones we use.

Homekit assumes it still has control over the last bulb it spoke to, but Alexa may have sent a command in the meantime. This means that Siri can end up setting the brightness/colour of the wrong bulb. A disaster when the baby is asleep 😆

For explanation: the plugin does not send an ON command (which is how the protocol 'announces' which bulb is to be controlled) before every colour/brightness command, only when it knows it is controlling a different bulb than it previously controlled.

Is there a way to re-enable the sending of (sometimes-) redundant ON commands? I have commented out the lines that check if the same bulb is being controlled, but it would really be better as a setting (per-bridge?)

OR is the general advice to just use Homekit/Homebridge and try to change the Habits of the Family?

Thanks for your work!!

**Comment by samsonrosen** [comment]
If you use the homebridge-Alexa plugin with Alexa it will control your Mi-Lights by homebridge rather than directly through the hub. That will keep the status accurate across homebridge/Alexa. I don’t think there’s an answer for the remotes.

**Comment by jameswood** [comment]
Thanks for your reply!

I tried homebridge-Alexa and it worked well but doesn't seem to support night-light mode, which is a dealbreaker for us. Your plugin works way better, and now that I've hacked it a bit it plays nicely with Alexa in my weird use-case. Ta!
