### ISSUE TITLE
Newby problem, Eve cant read LED Bulb Status

### ISSUE THREAD

**Issue by Bob1986** [dotsam/homebridge-milight#8]
Hello,

I´m a Newby with raspberry and I have an Issue with my milight setup.

I have an raspberry with zwave Modul and homebridge link.

The Milight bulb work in Eve and send corret commands to my RGBW Bulbs.

But EVE cant read the Status of the Bulbs correct.

When i turn the bulb on and restart the homebridge server than eve says the Bulb is off but the Bulb still lighning.

Is there a worktrough to get the right Status off my Light Bulb?

Best regards
Bob

**Comment by dotsam** [comment]
Hi @Bob1986,

Unfortunately not. The MiLight protocol is only one-way, so there's no ability to read the status from a bulb. HomeBridge keeps the status in memory when it's running, and ideally HomeBridge should be long-running, so this isn't an issue.
